# Wright Brothers :)
import numpy as np
from selenium import webdriver
import warnings
import time
import csv


def text_filter(text):

    start = 0
    stop = 0
    for i in range(len(text)-17):
        slice1 = text[i:i+6]
        slice2 = text[i:i+15]
        if slice1 == '/5000 ':
            start = i + 6

        if slice2 == '  Send feedback':
            stop = i

    text_needed = text[start:stop]
    return text_needed


def translate(my_input):

    # To ignore the warning generated by PhantomJS -- Not officially supported by Selenium
    warnings.filterwarnings("ignore")
    
    # Specify Language to be translated to
    language = 'en'

    # List of Languages supported
    f = open('./Assets/Language_List.csv', 'r')

    # Read data from csv file
    reader = csv.reader(f)
    lang_list = np.array([])
    for data in reader:
        lang_list = np.append(lang_list, data)

    # f = open('Language_List.csv','r')
    # Take input from the user and convert the language to lower for easy detection
    print('Please wait....')

    # Start measuring the time
    time_start = time.time()

    mylang = language.lower()

    # Find index of the desired language from the list
    # Set the url language code as per selected language
    index = np.where(lang_list == mylang)[0][0]
    if index % 2 == 0:
        to_lang = lang_list[index+1]
    else:
        to_lang = lang_list[index]

    # Construct the complete URL to search
    base_url = 'https://translate.google.com/#'
    # Enter from languge here 
    from_lang = 'ta'
    final_url = base_url + from_lang + '/' + to_lang

    # Initialize Selenium Driver
    # PhantomJS is used, Chrome is used.
    # driver = webdriver.PhantomJS('./Selenium Web Drivers/phantomjs.exe')
    # Please add exe to the end of the last string if running on windows.
    driver = webdriver.Chrome('./Selenium Web Drivers/chromedriver')

    # Perform operation to detect the translated text
    driver.set_page_load_timeout(30)        # In case Page doesn't load
    driver.get(final_url)                   # Search the URL
    driver.find_element_by_id('source').send_keys(my_input.lower())    # Input the Desired text to be translated
    # driver.find_element_by_class_name('gt-submit').click()          # Click on the translate button (not Mandatory)
    time.sleep(10)
    text_output = driver.find_element_by_tag_name('body')
    # text_output = driver.find_element_by_class_name('tlid-results-container results-container')
    # text_output = driver.find_element_by_id('tlid-translation translation')   # Get the output text

    time.sleep(1)   # Else it does not print the data

    # Stop Measuring the time
    time_end = time.time()
    time_taken = time_end - time_start  # Time required
    f.close()
    print('The amount of time taken to run the script is %.3f' % time_taken)
    #driver.quit()
    string = (text_output.text.replace("\n", " "))
    translated = text_filter(string)
    return translated

# Test Cases

myInput1 = 'மணியளவில் உதவி ஆய்வாளர் ஆகிய நான் நிலைய அலுவலில் இருக்கும் போது காவல் கட்டுப்பாட்டறையிலிருந்து வந்த தகவல் படி கங்காதீஸ்வரர் கோவில் தெரு கரூர் வைசியா பேங்க் முன்பு கீழ்பாக்கத்தில் மோட்டார் சைக்கிள் மற்றும் டிராக்டர் ஆகிய வாகனத்தில் விபத்து என்ற தகவலை பெற்று டீம் சகிதம் சம்பவ இடம் சென்று விசாரணை செய்ய விபத்தில் காயமடைந்த நபரை அரசு'
translated_text = translate(myInput1)

print(translated_text)
